#
# Docker-Compose - Menu Microservice
#

# @author - Benjamin Wong Wei En, Hao Jun Poon, Belle Lee, Chen Ziyi, Masturah Binte Sulaiman
# @team   - G3T4

version: '3.7'

services:

    order:
        build:
            context: ./app
            dockerfile: DOCKERFILE_MENU
        container_name: menu_microservice
        # ports:
        #     - "8000:8000"
        networks:
            - network
        environment: 
            - "URI=postgresql://easydeliverymenudb:easydeliverymenudbpassword@menu_db:5432/menu"
        # volumes:
        #     - 
        command: gunicorn -b 0.0.0.0:8000 app:app
        depends_on: 
            - menu_db
    
    order_db:
        image: postgres:12.2-alpine
        container_name: menu_postgres_database
        # ports:
        #     - "5432"
        networks:
            - network
        environment:
            MYSQL_DATABASE: OrderDB
            MYSQL_ROOT_PASSWORD: ordersecretpasswordwowomgsonice
            MYSQL_USER: orderdb
            MYSQL_PASSWORD: orderdbpassword
        volumes:
            - ./order/mysql:/docker-entrypoint-initdb.d/
        # command:
        # depends_on: 
        #     -
    
networks:
    network: 
        driver: "bridge"