#
# Docker-Build - EaSy Delivery Bot
#

# @author - Benjamin Wong Wei En, Hao Jun Poon, Belle Lee, Chen Ziyi, Masturah Binte Sulaiman, Low Louis
# @team   - G3T4

# pull the official Python image
FROM python:3.8.1-slim-buster

# set environment variables
# --- Prevents Python from writing pyc files to disc
ENV PYTHONDONTWRITEBYTECODE 1
# --- Prevents Python from buffering stdout and stderr
ENV PYTHONUNBUFFERED 1

# upgrade pip
RUN pip install --upgrade pip

# install dependencies
RUN pip install pika 
RUN pip install requests 
RUN pip install python-dotenv 
RUN pip install mysql-connector-python 
RUN pip install SQLAlchemy 
RUN pip install SQLAlchemy-Utils