#
# Docker-Compose - CRM Microservice
#

# @Author - Benjamin Wong Wei En, Hao Jun Poon, Belle Lee, Chen Ziyi, Masturah Binte Sulaiman
# @Team   - G3T4

version: '3.7'

services:

    crm:
        build:
            context: ./app
            dockerfile: DOCKERFILE_CRM
        container_name: crm_microservice
        # ports:
        #     - "8000:8000"
        networks:
            - network
        environment: 
            - "URI=postgresql://crmdb:crmdbpassword@crm_db:5432/crm"
        # volumes:
        #     -
        command: gunicorn -b 0.0.0.0:8000 app:app
        depends_on: 
            - crm_db
    
    crm_db:
        image: postgres:12.2-alpine
        container_name: crm_postgres_database
        # ports:
        #     - "5432"
        networks:
            - network
        environment:
            POSTGRES_DB: crm
            POSTGRES_USER: crmdb
            POSTGRES_PASSWORD: crmdbpassword
        volumes:
            - ./postgres:/docker-entrypoint-initdb.d/
        # command:
        # depends_on: 
    
    crm_nginx:
        image: nginx:1.17-alpine
        container_name: crm_nginx
        ports:
            - "88:80"
        networks:
            - network
        # environment: 
        #     -  
        volumes:
            - "./nginx:/etc/nginx/conf.d"  
        # command:  
        depends_on: 
            - crm
    
networks:
    network: 
        driver: "bridge"