version: '3.7'
services:

    recommendation:
        build:
            context: ./app
            dockerfile: DOCKERFILE_RECOMMENDATION
        container_name: recommendation_microservice
        # ports: (This exposes the port and we don't want that we want to expose the nginx port)
        #     - "8000"
        networks:
            - recommendation_microservice_network
        command: gunicorn -b 0.0.0.0:8000 app:app
        # environment: 
        #     - "URI=postgresql://crmdb:crmdbpassword@db:5432/crm" 
        # depends_on: 
        #     - db
    
    # db:
    #     image: postgres:12.2-alpine
    #     container_name: postgres_menu_database
    #     # ports:
    #     #     - "5432"
    #     networks:
    #         - recommendation_microservice_network
    #     environment:
    #         POSTGRES_DB: crm
    #         POSTGRES_USER: crmdb
    #         POSTGRES_PASSWORD: crmdbpassword
    
    nginx:
        build:
            context: ./nginx
            dockerfile: DOCKERFILE_NGINX
        container_name: nginx_server_recommendation
        ports:
            - "89:80"
        networks:
            - recommendation_microservice_network
        depends_on: 
            - recommendation
    
networks:
    recommendation_microservice_network: 
        driver: "bridge"