# Docker-Compose - Recommendation Microservice
# @Author - Benjamin Wong Wei En, Hao Jun Poon, Belle Lee, Chen Ziyi, Masturah Binte Sulaiman
# @Team   - G3T4

version: '3.7'

services:

    recommendation:
        build:
            context: ./app
            dockerfile: DOCKERFILE_RECOMMENDATION
        container_name: recommendation_microservice
        # ports:
        #     - "8000"
        networks:
            - network
        # environment: 
        #     -  
        # volumes:
        #     - 
        command: gunicorn -b 0.0.0.0:8000 app:app
        # depends_on: 
        #     - 
    
    recommendation_nginx:
        image: nginx:1.17-alpine 
        container_name: nginx_server_recommendation
        ports:
            - "89:80"
        networks:
            - network
        # environment: 
        #     -  
        volumes:
            - "./nginx:/etc/nginx/conf.d" 
        # command:
        depends_on: 
            - recommendation
    
networks:
    network: 
        driver: "bridge"