# pull official base image
FROM python:3.8.1-slim-buster

# set work directory
WORKDIR /app

# set environment variables
# --- Prevents Python from writing pyc files to disc
ENV PYTHONDONTWRITEBYTECODE 1
# --- Prevents Python from buffering stdout and stderr
ENV PYTHONUNBUFFERED 1

# update and install nginx
RUN apt-get update && apt-get -y upgrade 
# && apt-get install -y --no-install-recommends gcc nginx

# Move everything from the development folder to production folder
COPY . .

RUN pip install --upgrade pip

RUN pip install -r requirements.txt