version: '3.7'
services:

    rabbitmq:
        image: rabbitmq:3.8.3-management
        container_name: rabbitmq_broker
        ports:
            - "5672:5672"
            - "8080:15672"
        networks:
            - rabbitmq_broker_network
        environment:
            - RABBITMQ_DEFAULT_USER=rabbit
            - RABBITMQ_DEFAULT_PASS=tibbar  
    
networks:
    rabbitmq_broker_network: 
        driver: "bridge"