# Docker-Compose - RabbitMQ Broker
# @Author - Benjamin Wong Wei En, Hao Jun Poon, Belle Lee, Chen Ziyi, Masturah Binte Sulaiman
# @Team   - G3T4

version: '3.7'

services:

    rabbitmq:
        image: rabbitmq:3.8.3-management
        container_name: rabbitmq_broker
        ports:
            - "5673:5672"
            - "15673:15672"
        networks:
            - broker_network
        environment:
            - RABBITMQ_DEFAULT_USER=rabbit
            - RABBITMQ_DEFAULT_PASS=tibbar  
        # volumes:
        #     -
        # command:
        # depends_on: 
        #     - 
    
networks:
    broker_network: 
        driver: "bridge"