# Docker-Build - Payment Facilitation Microservice
# @Author - Benjamin Wong Wei En, Hao Jun Poon, Belle Lee, Chen Ziyi, Masturah Binte Sulaiman
# @Team   - G3T4

# pull the official PHP_FPM image
FROM php:7.4.3-fpm-buster

# install the bcmath dependency for stripe
RUN docker-php-ext-install bcmath