version: '3.7'
services:

    payment_facilitation:
        image: php:7.4.3-fpm-buster
        container_name: payment_facilitation_microservice
        volumes:
            - "./app:/var/www/app"
        networks:
            - payment_facilitation_network

    nginx_payment_facilitation:
        image: nginx:1.17-alpine
        container_name: nginx_server_payment_facilitation
        volumes:
            - "./app:/var/www/app"
            - "./nginx:/etc/nginx/conf.d"
        ports:
            - "86:80"
        networks:
            - payment_facilitation_network
        depends_on: 
            - payment_facilitation

    composer:
        image: composer
        container_name: composer_payment_facilitation
        volumes:
            - "./app:/app"
        privileged: True
        command: ["composer", "install"]

networks:
    payment_facilitation_network: 
        driver: "bridge"