#
# Docker-Compose - Payment Facilitation Microservice
#

# @Author - Benjamin Wong Wei En, Hao Jun Poon, Belle Lee, Chen Ziyi, Masturah Binte Sulaiman
# @Team   - G3T4

version: '3.7'

services:

    payment_facilitation:
        build:
            context: ./app
            dockerfile: DOCKERFILE_PAYMENT_FACILITATION
        container_name: payment_facilitation_microservice
        # ports:
        #     -
        networks:
            - network
        # environment: 
        #     - 
        volumes:
            - "./app:/var/www/app"
        # command:
        # depends_on: 
        #     -

    payment_facilitation_nginx:
        image: nginx:1.17-alpine
        container_name: payment_facilitation_nginx
        ports:
            - "86:80"
        networks:
            - network
        # environment: 
        #     - 
        volumes:
            - "./app:/var/www/app"
            - "./nginx:/etc/nginx/conf.d"
        # command:
        depends_on: 
            - payment_facilitation

    payment_facilitation_composer:
        image: composer
        container_name: payment_facilitation_composer
        # ports:
        #     - 
        networks:
            - network
        # environment: 
        #     - 
        volumes:
            - "./app:/app"
        privileged: True
        command: ["composer", "install"]

networks:
    network: 
        driver: "bridge"