# Docker-Compose - Menu Microservice
# @Author - Benjamin Wong Wei En, Hao Jun Poon, Belle Lee, Chen Ziyi, Masturah Binte Sulaiman
# @Team   - G3T4

version: '3.7'

services:

    menu:
        build:
            context: ./app
            dockerfile: DOCKERFILE_MENU
        container_name: menu_microservice
        # ports:
        #     - "8000:8000"
        networks:
            - network
        environment: 
            - "URI=postgresql://easydeliverymenudb:easydeliverymenudbpassword@menu_db:5432/menu"
        # volumes:
        #     - 
        command: gunicorn -b 0.0.0.0:8000 app:app
        depends_on: 
            - menu_db
    
    menu_db:
        image: postgres:12.2-alpine
        container_name: menu_postgres_database
        # ports:
        #     - "5432"
        networks:
            - network
        environment:
            POSTGRES_DB: menu
            POSTGRES_USER: easydeliverymenudb
            POSTGRES_PASSWORD: easydeliverymenudbpassword
        volumes:
            - ./postgres:/docker-entrypoint-initdb.d/
        # command:
        # depends_on: 
        #     -

    menu_nginx:
        image: nginx:1.17-alpine
        container_name: menu_nginx
        ports:
            - "85:80"
        networks:
            - network
        # environment: 
        #     -  
        volumes:
            - "./nginx:/etc/nginx/conf.d"
        # command:     
        depends_on: 
            - menu
    
networks:
    network: 
        driver: "bridge"