version: '3.7'
services:

    menu:
        build:
            context: ./app
            dockerfile: DOCKERFILE_MENU
        container_name: menu_microservice
        # ports: (This exposes the port and we don't want that we want to expose the nginx port)
        #     - "8000"
        networks:
            - menu_microservice_network
        command: gunicorn -b 0.0.0.0:8000 app:app
        environment: 
            - "URI=postgresql://easydeliverymenudb:easydeliverymenudbpassword@db:5432/menu" 
        depends_on: 
            - db
    
    db:
        image: postgres:12.2-alpine
        container_name: postgres_menu_database
        # ports:
        #     - "5432"
        networks:
            - menu_microservice_network
        environment:
            POSTGRES_DB: menu
            POSTGRES_USER: easydeliverymenudb
            POSTGRES_PASSWORD: easydeliverymenudbpassword
    
    nginx:
        build:
            context: ./nginx
            dockerfile: DOCKERFILE_NGINX
        container_name: nginx_server
        ports:
            - "85:80"
        networks:
            - menu_microservice_network
        depends_on: 
            - menu
    
networks:
    menu_microservice_network: 
        driver: "bridge"