#
# Docker-Compose - User Microservice
#

# @Author - Benjamin Wong Wei En, Hao Jun Poon, Belle Lee, Chen Ziyi, Masturah Binte Sulaiman, Low Louis
# @Team   - G3T4

version: '3.7'

services:

    user:
        build:
            context: ./app
            dockerfile: DOCKERFILE_USER
        container_name: user_microservice
        # ports:
        #     - "8000:8000"
        networks:
            - network
        environment: 
            - "URI=postgresql://userdb:userdbpassword@user_db:5432/user"
        # volumes:
        #     -
        command: gunicorn -b 0.0.0.0:8000 app:app
        depends_on: 
            - user_db
    
    user_db:
        image: postgres:12.2-alpine
        container_name: user_postgres_database
        # ports:
        #     - "5432"
        networks:
            - network
        environment:
            POSTGRES_DB: user
            POSTGRES_USER: userdb
            POSTGRES_PASSWORD: userdbpassword
        volumes:
            - ./postgres:/docker-entrypoint-initdb.d/
        # command:
        # depends_on: 
    
    user_nginx:
        image: nginx:1.17-alpine
        container_name: user_nginx
        ports:
            - "88:80"
        networks:
            - network
        # environment: 
        #     -  
        volumes:
            - "./nginx:/etc/nginx/conf.d"  
        # command:  
        depends_on: 
            - user
    
networks:
    network: 
        driver: "bridge"