version: '3.7'
services:

    ui:
        image: php:7.4.3-fpm-buster
        container_name: ui_container
        volumes:
            - "./app:/var/www/app"
        networks:
            - ui_network

    nginx_ui:
        image: nginx:1.17-alpine
        container_name: nginx_server_ui
        volumes:
            - "./app:/var/www/app"
            - "./nginx:/etc/nginx/conf.d"
            - "./certs:/etc/nginx/certs"
        ports:
            - "80:80"
            - "443:443"
        networks:
            - ui_network
        depends_on: 
            - ui

networks:
    ui_network: 
        driver: "bridge"